### ISSUE TITLE
Hard to react to the removal of a whitelisted attribute.

### ISSUE THREAD

**Issue by robCam** [webcomponents/shadydom#57] opened 2016-11-30 14:41 UTC
### Scenario:
For an older browser _(namely Google Chrome 49.0.2623.112)_ the following feature detection methods both return `false`:

``` javascript
const hasCustomElementsV1 = 'customElements' in window; // --> false
const hasShadowDOMV1 = !!HTMLElement.prototype.attachShadow; // --> false
```
To my understanding for this scenario the following three polyfills are required:

- [custom-elements.min.js](https://github.com/webcomponents/custom-elements)
- [shadydom.min.js](https://github.com/webcomponents/shadydom)
- [shadycss.min.js](https://github.com/webcomponents/shadycss)

### Issue encountered: 
With these three polyfills loaded and detecting the removal of an attribute via the `attributeChangedCallback` of an autonomous custom element class. For example.

``` javascript
attributeChangedCallback(name, oldValue, newValue) {
    if (name === 'value' && newValue === null) {
        // Logic for reacting to the 'value' attribute being removed goes here.
        console.log('value attribute has been removed');
        ... 
    }
}
```

...subsequently then removing an element attribute, one which has been whitelisted in the `observedAttributes` array. E.g.

``` javascript
document.querySelector('my-snazzy-element').removeAttribute('value');
```
Results in the '_value attribute has been removed_'  to be logged **twice** to the console.

This makes it hard to react to an attribute being removed because of the second call. Any logic added here is currently being called twice.

### Further info:
When loading only the `custom-elements.min.js` polyfill for a newer browser, _(namely mobile Safari/602.1)_, whereby feature detection reports.

``` javascript
const hasCustomElementsV1 = 'customElements' in window; // --> false
const hasShadowDOMV1 = !!HTMLElement.prototype.attachShadow; // --> true
```

As expected, when removing an element (without `shadydom.min.js` and `shadycss.min.js` polyfills loaded). For example:

``` javascript
document.querySelector('my-snazzy-element').removeAttribute('value');
```

 ...the _'value attribute has been removed'_ is correctly only logged **once** to the console.

**Comment by sorvell** [comment] 2017-04-21 18:13
Sorry for the delay on this, but it looks like this is now working ok as shown here:
 It looks like this is working as intended now and the issue does not reproduce here: 

Going to close this. Please re-open with additional info if necessary.

**Closed** 2017-04-21 18:14 UTC
Labels: p1

**Comment by robCam** [comment] 2017-04-24 13:57
Thank you @sorvell for the update and associated gist regarding this issue.
Just confirming that utilizing the revised _(+ additional)_ polyfills resolves this issue successfully for me. Cheers!

:thumbsup:
